name: 'AWS CDK GitHub Actions dotnet6'
description: 'Runs AWS-CDK via GitHub Actions.'
author: 'verdurakh(verdurakh@gmail.com)'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  cdk_stack:
    description: 'AWS CDK stack name to execute.'
    default: '*'
  cdk_version:
    description: 'AWS CDK version to install.'
    default: 'latest'
  cdk_subcommand:
    description: 'AWS CDK subcommand to execute.'
    required: true
  working_dir:
    description: 'AWS CDK working directory.'
    default: '.'
outputs:
  status_code:
    description: 'Returned status code.'
runs:
  using: 'docker'
  image: './Dockerfile'
